name: CroissantSys
version: '${version}'
main: com.github.sheauoian.croissantsys.CroissantSys
api-version: '1.20'

depend:
    - ProtocolLib
    - NBTAPI
    - MythicMobs
    - HologramAPI
    - DecentHolograms

commands:
    croissant:
        description: CroissantSys のメインコマンドです
    item:
        description: Sleep Item を統括します
    user:
        description: Sleep User を統括します
    storage:
        description: Storage を開きます
    warp_point:
        description: WarpPoint を統括します
    warp:
        description: Warp します
    equipment:
        description: Equipment