name: CroissantSys
version: '${version}'
main: com.github.sheauoian.croissantsys.CroissantSys
api-version: '1.20'

depend:
    - ProtocolLib
    - NBTAPI
    - MythicMobs
    - HologramAPI
    - DecentHolograms